WELCOME_MESSAGE: Welcome to our Photobooth
BACKGROUND_IMAGE: backgrounds/Landingpage.png        # remember to add your custom background image to ui/resources.qrc before specifing it here
WELCOME_TEXT_COLOR: rgb(247, 244, 183)
IMAGE_BORDER_COLOR: rgb(247, 244, 183)

TARGET_DIR: data/images

COUNTDOWN_TIME_SECONDS: 5
PREVIEW_TIME_SECONDS: 50

COUNTDOWN_SOUND: ui/sounds/countdown_ping.wav

PRINTER_NAME: Dai_Nippon_Printing_DP_DS620
CAMERA_INDEX: 1

SHOW_COLLAGE: True
SHOW_DELETE: True
SHOW_PRINT: True
SHOW_RECAPTURE: True
SHOW_SHARE: False
SHOW_BUTTON_TEXT: False