WELCOME_MESSAGE: Welcome to our Photobooth
BACKGROUND_IMAGE: backgrounds/Landingpage.png        # remember to add your custom background image to ui/resources.qrc before specifing it here
WELCOME_TEXT_COLOR: rgb(247, 244, 183)
IMAGE_BORDER_COLOR: rgb(247, 244, 183)

TARGET_DIR: data/images

COUNTDOWN_TIME_SECONDS: 5
PREVIEW_TIME_SECONDS: 20

COUNTDOWN_SOUND: ui/sounds/countdown_ping.wav

PRINTER_NAME: CP400
CAMERA_INDEX: 0

SHOW_CHALLENGE: False
SHOW_COLLAGE: False
SHOW_DELETE: True
SHOW_PRINT: False
SHOW_RECAPTURE: True
SHOW_SHARE: False
SHOW_BUTTON_TEXT: False